# AD9238 引脚约束，对应开发板扩展口J21
set_property PACKAGE_PIN J16 [get_ports adc_clk_ch0]
set_property PACKAGE_PIN F16 [get_ports {adc_data_ch0[1]}]
set_property PACKAGE_PIN F17 [get_ports {adc_data_ch0[0]}]
set_property PACKAGE_PIN H20 [get_ports {adc_data_ch0[3]}]
set_property PACKAGE_PIN J20 [get_ports {adc_data_ch0[2]}]
set_property PACKAGE_PIN G18 [get_ports {adc_data_ch0[5]}]
set_property PACKAGE_PIN G17 [get_ports {adc_data_ch0[4]}]
set_property PACKAGE_PIN H17 [get_ports {adc_data_ch0[7]}]
set_property PACKAGE_PIN H16 [get_ports {adc_data_ch0[6]}]
set_property PACKAGE_PIN G15 [get_ports {adc_data_ch0[9]}]
set_property PACKAGE_PIN H15 [get_ports {adc_data_ch0[8]}]
set_property PACKAGE_PIN K18 [get_ports {adc_data_ch0[11]}]
set_property PACKAGE_PIN K17 [get_ports {adc_data_ch0[10]}]

set_property PACKAGE_PIN M18 [get_ports adc_clk_ch1]
set_property PACKAGE_PIN M17 [get_ports {adc_data_ch1[0]}]
set_property PACKAGE_PIN K19 [get_ports {adc_data_ch1[1]}]
set_property PACKAGE_PIN J19 [get_ports {adc_data_ch1[2]}]
set_property PACKAGE_PIN B19 [get_ports {adc_data_ch1[3]}]
set_property PACKAGE_PIN A20 [get_ports {adc_data_ch1[4]}]
set_property PACKAGE_PIN B20 [get_ports {adc_data_ch1[5]}]
set_property PACKAGE_PIN C20 [get_ports {adc_data_ch1[6]}]
set_property PACKAGE_PIN G19 [get_ports {adc_data_ch1[7]}]
set_property PACKAGE_PIN G20 [get_ports {adc_data_ch1[8]}]
set_property PACKAGE_PIN M19 [get_ports {adc_data_ch1[9]}]
set_property PACKAGE_PIN M20 [get_ports {adc_data_ch1[10]}]
set_property PACKAGE_PIN D20 [get_ports {adc_data_ch1[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_ch0]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_ch0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_ch1]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_ch1[*]}]

# 多路复用器模块的引脚约束，对应开发板扩展口J20的21-39脚
# 21、23、25、27、29、31、33、35脚：cmp_in_ch0[0]-cmp_in_ch0[7]
# 22、24、26、28、30、32、34、36脚：cmp_in_ch1[0]-cmp_in_ch1[7]
set_property PACKAGE_PIN V16 [get_ports {cmp_in_ch0[0]}]
set_property PACKAGE_PIN R18 [get_ports {cmp_in_ch0[1]}]
set_property PACKAGE_PIN W19 [get_ports {cmp_in_ch0[2]}]
set_property PACKAGE_PIN W20 [get_ports {cmp_in_ch0[3]}]
set_property PACKAGE_PIN P20 [get_ports {cmp_in_ch0[4]}]
set_property PACKAGE_PIN U17 [get_ports {cmp_in_ch0[5]}]
set_property PACKAGE_PIN U20 [get_ports {cmp_in_ch0[6]}]
set_property PACKAGE_PIN V15 [get_ports {cmp_in_ch0[7]}]
set_property PACKAGE_PIN W16 [get_ports {cmp_in_ch1[0]}]
set_property PACKAGE_PIN T17 [get_ports {cmp_in_ch1[1]}]
set_property PACKAGE_PIN W18 [get_ports {cmp_in_ch1[2]}]
set_property PACKAGE_PIN V20 [get_ports {cmp_in_ch1[3]}]
set_property PACKAGE_PIN N20 [get_ports {cmp_in_ch1[4]}]
set_property PACKAGE_PIN T16 [get_ports {cmp_in_ch1[5]}]
set_property PACKAGE_PIN T20 [get_ports {cmp_in_ch1[6]}]
set_property PACKAGE_PIN W15 [get_ports {cmp_in_ch1[7]}]
# 13、15、17、19脚：mux_sel_ch0[0] mux_sel_en_ch0 mux_sel_en[2] mux_sel_ch0[1]
# 14、16、18、20脚：mux_sel_ch1[0] mux_sel_en_ch1 mux_sel_en[2] mux_sel_ch1[1]
set_property PACKAGE_PIN P19 [get_ports {mux_sel_ch0[0]}]
set_property PACKAGE_PIN R17 [get_ports mux_sel_en_ch0]
set_property PACKAGE_PIN P15 [get_ports {mux_sel_ch0[2]}]
set_property PACKAGE_PIN N17 [get_ports {mux_sel_ch0[1]}]
set_property PACKAGE_PIN N18 [get_ports {mux_sel_ch1[0]}]
set_property PACKAGE_PIN R16 [get_ports mux_sel_en_ch1]
set_property PACKAGE_PIN P16 [get_ports {mux_sel_ch1[2]}]
set_property PACKAGE_PIN P18 [get_ports {mux_sel_ch1[1]}]
# 多路复用器模块的IO标准设置
set_property IOSTANDARD LVCMOS33 [get_ports {cmp_in_ch0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmp_in_ch1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mux_sel_ch0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports mux_sel_en_ch0]
set_property IOSTANDARD LVCMOS33 [get_ports {mux_sel_ch1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports mux_sel_en_ch1]



set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]
set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
